### ISSUE TITLE
Can not find the metrics 

### ISSUE THREAD

**Issue by masterminh219** [JamesNK/aspnetcore-grafana#1] opened 2023-06-12 17:10 UTC
The dashboard does not work due to there is no metrics has been exposed
'`.AddAspNetCoreInstrumentation()
        .AddHttpClientInstrumentation()
        .AddRuntimeInstrumentation()
        .AddProcessInstrumentation()
        .AddPrometheusExporter())`

If I can add this one with instrumentation then it works but the metric name is different from  `request_duration_s_count`

**Comment by ErisApps** [comment] 2023-07-22 11:37
Most of the metrics can be fixed by adding either prefix `http_server_` or `kestrel_` in the Grafana dashboard, although I haven't gotten the ones that use the `exception_name` metric field to work just yet.

Also seems to be mainly caused by this PR at first sight?
https://github.com/dotnet/aspnetcore/pull/48375

**Comment by JamesNK** [comment] 2023-08-21 14:24
The counter names are changing during .NET 8. Hopefully, they have stabilized.

I've updated the dashboards to use what is in daily SDKs and the upcoming .NET 8 release candidate 1.

**Comment by JamesNK** [comment] 2023-11-21 02:08
Dashboards fully updated for .NET 8.

FYI dashboard source code now lives at https://aka.ms/dotnet/grafana-source

**Closed by JamesNK** 2023-11-21 02:08 UTC
